mime_map = {
    'jpg': 'image/jpeg',
    'png': 'image/png',
    'gif': 'image/gif',
    'bmp': 'image/x-ms-bmp',
    'mp3': 'audio/mpeg',
    'aif': 'audio/x-aif',
    'aiff': 'audio/x-aif',
    'aifc': 'audio/x-aif',
    'wav': 'audio/x-wav',
    'avi': 'video/x-msvideo',
    'pdf': 'application/pdf',
    'mov': 'video/quicktime',
    'qt': 'video/quicktime',
    'zip': 'application/zip',
    'exe': 'application/octet-stream',
    'tar': 'application/octet-stream',
    'bin': 'application/octet-stream',
    'uu': 'application/octet-stream',
    'rtf': 'application/rtf',
    'txt': 'text/plain',
    'doc': 'application/msword',
    'ps': 'application/postscript',
    'eps': 'application/postscript',
    'ai': 'application/postscript'
}
